
%% Menú de escolha de tratamento para zona de libertação


fig_deb=figure('Position',[578 204 207 473],...
'Color',[0 0.5 0.5],...
'Name','',...
'NumberTitle','off',...
'Visible','on', ...
'Resize','on', ...
'MenuBar','none');

box_fil=uicontrol(fig_deb,'style','text',...
'BackGroundColor',[0 0.5 0.5],...
'ForeGroundColor',[1 1 1],...
'string',' Tipo de tratamento ("aut", "itr" ou "man"):','position',[38.5 264 130 25]);

box_edfil=uicontrol(fig_deb,'style','edit',...
'string',num2str(opcao.tratpha),'position',[48.5 224 110 25],...
'BackGroundColor',[1 1 1],...
'Tag','EditText0');


convnext=uicontrol(fig_deb,...
'BackGroundColor',[0 1 1],...
'ForeGroundColor',[0 0.5 0.5],...
'style','push',...
'string','Continuar',...
'position',[58.5 164 90 25],...
'callback',['EditHandle=findobj(gcbf,''Tag'',''EditText0'');',...
'opcao.tratpha=get(EditHandle,''String'');close(gcf)']);