
%% Menú de escolha da directoria de trabalho para a
%% opção série de tratamento.


fig_trab=figure('Position',[578 204 207 473],...
'Color',[0 0.5 0.5],...
'Name','',...
'NumberTitle','off',...
'Visible','on', ...
'Resize','on', ...
'MenuBar','none');

box=uicontrol(fig_trab,'style','text',...
'BackGroundColor',[0 0.5 0.5],...
'ForeGroundColor',[1 1 1],...
'string',' Directoria de trabalho:','position',[48.5 298 110 25]);


box_edit=uicontrol(fig_trab,'style','edit',...
'string',num2str(opcao.direct),'position',[8.5 244 190 25],...
'BackGroundColor',[1 1 1],...
'Tag','EditText1');


convnext=uicontrol(fig_trab,...
'BackGroundColor',[0 1 1],...
'ForeGroundColor',[0 0.5 0.5],...
'style','push',...
'string','Continuar',...
'position',[58.5 184 90 25],...
'callback',['EditHandle=findobj(gcbf,''Tag'',''EditText1'');',...
'opcao.direct=get(EditHandle,''String'');close(gcf)']);

