
%% Menú de escolha pré-tratamento por filtro wiener


fig_avc=figure('Position',[578 204 207 473],...
'Color',[0 0.5 0.5],...
'Name','',...
'NumberTitle','off',...
'Visible','on', ...
'Resize','on', ...
'MenuBar','none');

box=uicontrol(fig_avc,'style','text',...
'BackGroundColor',[0 0.5 0.5],...
'ForeGroundColor',[1 1 1],...
'string',' Pré-tratamento:','position',[48.5 298 110 25]);

if opcao.pretrat=='sim'
box_ser=uicontrol(fig_avc,'style','radio',...
'BackGroundColor',[0 0.5 0.5],...
'ForeGroundColor',[1 1 1],...
'string',' Sim','position',[48.5 244 110 25],'value',1,...
'callback',['if get(box_ser,''value'')==1,',...
'set(box_img,''value'',0),','opcao.pretrat=''sim'';','else set(box_img,''value'',1),','opcao.pretrat=''nao'';','end']);

box_img=uicontrol(fig_avc,'style','radio',...
'BackGroundColor',[0 0.5 0.5],...
'ForeGroundColor',[1 1 1],...
'string',' Não','position',[48.5 184 110 25],...
'callback',['if get(box_img,''value'')==1,',...
'set(box_ser,''value'',0),','opcao.pretrat=''nao'';','else set(box_ser,''value'',1),','opcao.pretrat=''sim'';','end']);
else
box_ser=uicontrol(fig_avc,'style','radio',...
'BackGroundColor',[0 0.5 0.5],...
'ForeGroundColor',[1 1 1],...
'string',' Sim','position',[48.5 244 110 25],...
'callback',['if get(box_ser,''value'')==1,',...
'set(box_img,''value'',0),','opcao.pretrat=''sim'';','else set(box_img,''value'',1),','opcao.pretrat=''nao'';','end']);

box_img=uicontrol(fig_avc,'style','radio',...
'BackGroundColor',[0 0.5 0.5],...
'ForeGroundColor',[1 1 1],...
'string',' Não','position',[48.5 184 110 25],'value',1,...
'callback',['if get(box_img,''value'')==1,',...
'set(box_ser,''value'',0),','opcao.pretrat=''nao'';','else set(box_ser,''value'',1),','opcao.pretrat=''sim'';','end']);
end


convnext=uicontrol(fig_avc,...
'BackGroundColor',[0 1 1],...
'ForeGroundColor',[0 0.5 0.5],...
'style','push',...
'string','Continuar',...
'position',[58.5 124 90 25],...
'callback','close(gcf)');
