
%% Menú de escolha dos limites manuais de deteção

fig_det = figure( ...
'Position',[578 204 207 473], ...
'Color',[0 0.5 0.5], ...
'Name','', ...
'NumberTitle','off', ...
'Visible','on', ...
'Resize','on', ...
'MenuBar','none');

box = uicontrol(fig_det, ...
'style','text', ...
'BackGroundColor',[0 0.5 0.5], ...
'ForeGroundColor',[1 1 1], ...
'string',' Limites manuais:', ...
'position',[38.5 464 130 25]);

%% threshold fluorescência

box0 = uicontrol(fig_det, ...
'style','text', ...
'BackGroundColor',[0 0.5 0.5], ...
'ForeGroundColor',[1 1 1], ...
'string',' Threshold fluorescência:', ...
'position',[25 404 160 25]);

box_edit0 = uicontrol(fig_det, ...
'style','edit', ...
'string',num2str(opcao.thrpp), ...
'position',[48.5 384 110 25], ...
'BackGroundColor',[1 1 1], ...
'Tag','EditText0');

%% filtro intensidade

box1 = uicontrol(fig_det, ...
'style','text', ...
'BackGroundColor',[0 0.5 0.5], ...
'ForeGroundColor',[1 1 1], ...
'string',' Filtro intensidade:', ...
'position',[25 324 160 25]);

box_edit1 = uicontrol(fig_det, ...
'style','edit', ...
'string',num2str(opcao.thredgp), ...
'position',[48.5 304 110 25], ...
'BackGroundColor',[1 1 1], ...
'Tag','EditText1');

%% filtro partículas

box2 = uicontrol(fig_det, ...
'style','text', ...
'BackGroundColor',[0 0.5 0.5], ...
'ForeGroundColor',[1 1 1], ...
'string',' Filtro partículas:', ...
'position',[25 244 160 25]);

box_edit2 = uicontrol(fig_det, ...
'style','edit', ...
'string',num2str(opcao.thrlibp), ...
'position',[48.5 224 110 25], ...
'BackGroundColor',[1 1 1], ...
'Tag','EditText2');

%% botão continuar

convnext = uicontrol(fig_det, ...
'BackGroundColor',[0 1 1], ...
'ForeGroundColor',[0 0.5 0.5], ...
'style','push', ...
'string','Continuar', ...
'position',[58.5 84 90 25], ...
'callback',[ ...
'EditHandle=findobj(gcbf,''Tag'',''EditText0'');' ...
'opcao.thrpp=str2num(get(EditHandle,''String''));' ...
'EditHandle=findobj(gcbf,''Tag'',''EditText1'');' ...
'opcao.thredgp=str2num(get(EditHandle,''String''));' ...
'EditHandle=findobj(gcbf,''Tag'',''EditText2'');' ...
'opcao.thrlibp=str2num(get(EditHandle,''String''));' ...
'close(gcf)']);