function final(opcao)

%% ------------------------------------------------------------------------
% Menu final
%% ------------------------------------------------------------------------

fig_fim = figure( ...
    'Position',[578 204 207 473], ...
    'Color',[0 0.5 0.5], ...
    'Name','Fim', ...
    'NumberTitle','off', ...
    'Visible','on', ...
    'Resize','off', ...
    'MenuBar','none');

%% ------------------------------------------------------------------------
% Texto
%% ------------------------------------------------------------------------

uicontrol( ...
    fig_fim, ...
    'style','text', ...
    'BackGroundColor',[0 0.5 0.5], ...
    'ForeGroundColor',[1 1 1], ...
    'string','Outra(s) Imagem(ns)?', ...
    'position',[48.5 298 110 25]);

%% ------------------------------------------------------------------------
% Botão SIM
%% ------------------------------------------------------------------------

uicontrol( ...
    fig_fim, ...
    'BackGroundColor',[0 1 1], ...
    'ForeGroundColor',[0 0.5 0.5], ...
    'style','push', ...
    'string','Sim', ...
    'position',[58.5 244 90 25], ...
    'callback', @(src,event) abrirNova(opcao, fig_fim));

%% ------------------------------------------------------------------------
% Botão NÃO
%% ------------------------------------------------------------------------

uicontrol( ...
    fig_fim, ...
    'BackGroundColor',[0 1 1], ...
    'ForeGroundColor',[0 0.5 0.5], ...
    'style','push', ...
    'string','Não', ...
    'position',[58.5 184 90 25], ...
    'callback', @(src,event) fecharTudo(fig_fim));

end

%% ------------------------------------------------------------------------
% Abrir nova imagem
%% ------------------------------------------------------------------------

function abrirNova(opcao, fig_fim)

close(fig_fim);

adquirir(opcao);

end

%% ------------------------------------------------------------------------
% Fechar tudo
%% ------------------------------------------------------------------------

function fecharTudo(fig_fim)

close(fig_fim);

close all;

clc;

end

