%% Programa para deteção de microplásticos fluorescentes

clear all, close all, clc

fig_princ = figure( ...
'Name','Microplasticos', ...
'Color',[0 0.5 0.5], ...
'Position',[5 204 566 456], ...
'NumberTitle','off', ...
'Visible','off', ...
'Resize','off', ...
'MenuBar','none', ...
'Colormap',[gray]);

close(1)

[IMAGEM_ABRT] = imread('imagin.bmp');
IMAGEM_ABRT = mat2gray(double(IMAGEM_ABRT));

figure('MenuBar','none');

imshow(IMAGEM_ABRT, 'InitialMagnification', 'fit')
pause(1)

colormap(copper)

%% opções principais

opcao = struct( ...
    'avanco','series', ...
    'deconv','nao', ...
    'pretrat','sim', ...
    'tratpha','itr', ...
    'tratgrp','itr', ...
    'thrpp',0.35, ...
    'thredgp',0.5, ...
    'thrlibp',0.35, ...
    'fluor','red');

opcao.direct = [cd,'\'];
opcao.direct_ant = cd;

%% menus

men_img = uimenu(gcf,'label','Imagem');

men_abr = uimenu(men_img, ...
'label','Abrir', ...
'callback','adquirir(opcao)');

men_sai = uimenu(men_img, ...
'label','Sair', ...
'callback','final(opcao)');

men_avc = uimenu(gcf,'label','Avanço');

men_ser = uimenu(men_avc, ...
'label','Série/Imagem a Imagem', ...
'callback','esc_avc');

men_flr = uimenu(gcf,'label','Fluorescência');

men_chn = uimenu(men_flr, ...
'label','Red/Orange', ...
'callback','esc_flr');

men_trat = uimenu(gcf,'label','Tratamento');

men_prt = uimenu(men_trat, ...
'label','Pré-tratamento', ...
'callback','esc_pre');

men_trtl = uimenu(men_trat, ...
'label','Tratamento fluorescência', ...
'callback','esc_trtl');

men_trtg = uimenu(men_trat, ...
'label','Tratamento partículas', ...
'callback','esc_trtg');

men_dcv = uimenu(men_trat, ...
'label','Desconvolução', ...
'callback','esc_dcv');

men_lim = uimenu(men_trat, ...
'label','Limites manuais', ...
'callback','esc_lim');